---
separator:
  - dev
  - feat
  - rel

role:
  - application
  - dba
  - privileged
  - readonly
  - schema

permission:
  - database:
      - connect
      - create
      - temporary
      - usage
  - function:
      - execute
  - table:
      - delete
      - insert
      - references
      - select
      - trigger
      - truncate
      - update

grant:
  - connect:
      - application
      - dba
      - privileged
      - readonly
      - schema
  - create:
      - dba
      - schema
  - delete:
      - application
      - dba
      - privileged
      - schema
  - execute:
      - application
      - dba
      - privileged
      - readonly
      - schema
  - insert:
      - application
      - dba
      - privileged
      - schema
  - references:
      - dba
      - schema
  - select:
      - application
      - dba
      - privileged
      - readonly
      - schema
  - trigger:
      - dba
      - schema
  - truncate:
      - dba
      - schema
  - update:
      - application
      - dba
      - privileged
      - schema

# Example of how to lay out custom restrictions
#
# custom:
#   - dbname:
#     - schemaname:
#       - tablename:
#         - columnname:
#           - privileged
#
#   - dbname:
#     - schemaname:
#       - tablename:
#         - privileged
#         - dba
